### ISSUE TITLE
Import without text conversion?

### ISSUE THREAD

**Issue by philippspengler** [jamesf91/RemarkableSync#10]
Would it be possible to implement this add-on without the text conversion so that the lines are imported as lines into OneNote (best scenario would be for these do be editable in OneNote, but adding as an image is also sufficient)?

**Comment by totalitarian** [comment]
I 2nd this request please

**Comment by tommyittu** [comment]
I would love this too!

**Comment by jamesf91** [comment]
I will give this a go but it might take a while as I don't have much experience in working with images in c#

**Comment by jamesf91** [comment]
This feature is implemented in version 2.0.4
https://github.com/jamesf91/RemarkableSync/releases/tag/2.0.4
