### ISSUE TITLE
Installation not working v2.0.4

### ISSUE THREAD

**Issue by philippspengler** [jamesf91/RemarkableSync#12]
The installer runs without issue but the add-in does not show up in OneNote (no add-ins in the option menu and nothing in the toolbar). Using the x86 installer in 64-bit OneNote. Also tried the x64 installer but this didn't work either.

I uninstalled the previous version within OneNote to update (remove COM-addin) and then removed the installer through Windows, so perhaps that caused the plug-in to no longer be recognized by OneNote upon reinstallation.

**Comment by jamesf91** [comment]
Umm, that's strange. 

Usually I just run the latest installer directly and it will upgrade the existing instance. I'm not sure what "removing COM-addin" from wihtin OneNote does, It's possible that it just disables the addin. 

Can you still see RemarkableSync at all in the Add-in options page in OneNote?

**Comment by philippspengler** [comment]
No, it doesn't show up under the add-ins at all. Is there a specific folder where I have to install the add-in?

**Comment by tommyittu** [comment]
I am facing the same issue. I initially ran the updater but there was not difference in the add-in. So I removed using the add-in using Remove Add In from options. Ran the installer again, it runs without issue but the Remarkable tab does not appear.

**Comment by philippspengler** [comment]
I've managed to make the installation work. I had to run a full repair of OneNote through the Office installer (basically a reinstall). After that the install worked without issues.
