### ISSUE TITLE
[Feature Request] Graphics and Text fetch in one click

### ISSUE THREAD

**Issue by spyro-k** [jamesf91/RemarkableSync#17]
With 2.0.4 welcome feature of "Adding option to the download dialog to import pages as image rather than text.", I find myself always Fetching twice, one in Graphics and one in Text mode, and then copy-paste them in the same OneNote sheet... is it possible to add an option to Fetch both in "Graphics and Text" mode and place them in a single OneNote sheet?

**Comment by jamesf91** [comment]
#30
