### ISSUE TITLE
[Feature Request] Set default image width size on Fetch

### ISSUE THREAD

**Issue by spyro-k** [jamesf91/RemarkableSync#18]
Is it possible to add an option to import the Graphics format as XYZ pixels wide? The current import is very wide (and super-readable of course) but requires more scrolling. Default should be the current pixel width of course, for those that prefer it in this size

**Comment by jamesf91** [comment]
Added spinner to set graphics import width. Available in version 2.0.6 onwards.

![image](https://user-images.githubusercontent.com/2037620/154841428-eb5b5d39-c66b-4da3-93db-e7cdbc050918.png)

**Comment by spyro-k** [comment]
This works great, thank you so much!

At the next opportunity, it would be great if the width would remember my previous entry (I like 25% for example), or add the Width % in the Settings.

Regards,
Spyro
