### ISSUE TITLE
"Error importing document from reMarkable. Object reference not set to instance of an object."

### ISSUE THREAD

**Issue by philippspengler** [jamesf91/RemarkableSync#21]
I receive the following error message when trying to import a document in the newest version.

**Comment by jamesf91** [comment]
I did get the same error using cloud download just then. SSH is still fine. 
I will look into the issue, Hopefully reMarkable didn't recently change the way files are structured in the cloud.

**Comment by rickabens** [comment]
I got the same error.  Any update?

**Comment by jamesf91** [comment]
Hey, sorry for the delay. This issue has been fixed from version 2.0.6 onwards

**Comment by rickabens** [comment]
Great. I will install v2.0.6.  it's a nice app.  Thanks

Rick


Rick Abens

CEO & Founder

Foresight ROI, Inc.

+1 (312) 575-0024<tel:+13125750024>

________________________________
