### ISSUE TITLE
reMarkableSync not downloading Template layer

### ISSUE THREAD

**Issue by Shrekmachine** [jamesf91/RemarkableSync#22]
Hi, got my rm2 today. Trying to import some notes with template layers I failed. The template layer is not downloaded, only the handwriting.
Works as designed or did I miss a step?

**Comment by jamesf91** [comment]
Hi Shrekmachine, that is currently working as designed as the template was always an image layer that's stored separately on the device and superimposed over the top.
I might look into getting the template image in future but it's not on the immediate scope of new features.

**Comment by Shrekmachine** [comment]
Thanks for sharing your thoughts and plans. 
unfortunately for me that would be THE feature. 
Thinking of meeting protocols an unstructured view and even the transformation into digital text is not helpful :(
