### ISSUE TITLE
French text conversion does'nt work well

### ISSUE THREAD

**Issue by sebastienpiconnier** [jamesf91/RemarkableSync#25]
Hello,
Is possible to add french text conversion ? Remarkable use the same APi from Myscript  and works well for French conversion. A stand-alone app for conversion will be nice too.
Many Thanks !

**Comment by bush3r** [comment]
I was looking for it too. This file is responsible of sending HTTP request to myscript.com `reMarkableSync/RemarkableSync/MyScriptClient.cs`
I guess we also need to send the `lang` parameter  from `Configuration` section with the request (according to myscript REST API https://swaggerui.myscript.com/)
