### ISSUE TITLE
GetAllItems request failed with status code Unauthorized

### ISSUE THREAD

**Issue by Nile22** [jamesf91/RemarkableSync#28]
Hello,

I get the error "GetAllItems request failed with status code Unauthorized" with last version 2.0.6 x64.

I generated a new One Time code unsuccessfullly.

Am I the only one ?

Thank you

**Comment by ofreiheit** [comment]
Hi, I have exactly the same issue with 2.0.6 x86. Could you fix your problem?

Thanks

**Comment by cplager** [comment]
I installed and it worked fine the first day.  

I installed on second computer and got 
![image](https://user-images.githubusercontent.com/17601058/160253327-9c8075d5-4e89-4b9c-ac03-5f36b096326a.png)

When i went back to first computer, I now get same error.

On both computers, I tried re-authorizing, but no luck.

**Comment by kcossabo** [comment]
Same issue here :(

Looks cool, but fails

**Comment by jamesf91** [comment]
Hey guys, sorry I've been pretty busy with other things recently. 
I have not been able to reproduce this issue using OneNote linked to my remarkable account.

I just published version 2.0.7 which has the ability to optionally generate log files that should provide more info on the error.
Please follow the instruction in the troubleshoot section of the main readme to enable logging and reproduce the problem. 

You can send me a private message with the log of the issue and I can have a look.

**Comment by kcossabo** [comment]
I may have screwed up, but, it is definitely broken.

1) Installed new version over old (no uninstall)
2) Added the RegKey
3) open onenote, addin is not present
4) series of trouble shooting, involving, repair that version, remove, go back to old version, reinstall, for everyone, just for me

Can not get the ribbon to show the addin, also, the install does not create the regKey anymore (the base one with out the LogFile)

**Comment by kcossabo** [comment]
James

Have the log file, how do I PM you?

I will include it here. I ran it once after I messed up reinstalls, failed, then redid the setup keys and failed. 9:20 first fail, 9:34 second after redoing the tokens

`4/15/2022 9:20:38 AM	AddIn.GetCustomUI(79) - called
4/15/2022 9:20:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "RmConnectionMethod" failed
4/15/2022 9:20:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "CustomDeviceTokenUrl" failed
4/15/2022 9:20:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "CustomUserTokenUrl" failed
4/15/2022 9:20:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "CustomBaseUrl" failed
4/15/2022 9:20:44 AM	RmDownloadForm.InitializeData(91) - Using rm cloud data source
4/15/2022 9:20:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "rmdevicetoken" failed
4/15/2022 9:20:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "rmusertoken" failed
4/15/2022 9:20:44 AM	RmCloudDataSource.Request(212) - url is: https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs
4/15/2022 9:20:44 AM	RmCloudDataSource.GetAllItems(116) - Request failed with status code: Unauthorized and content: Serving request failed, Msg: missing authentication token, Origin: missing authentication token, HTTPCode: 401

4/15/2022 9:20:44 AM	RmDownloadForm.InitializeData(99) - Error getting notebook structure from reMarkable. Err: GetAllItems request failed with status code Unauthorized
4/15/2022 9:29:44 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "RmConnectionMethod" failed
4/15/2022 9:29:44 AM	SettingsForm.setRmConnectionMethod(162) - Setting connection method to RmCloud
4/15/2022 9:30:53 AM	RmCloudDataSource.RegisterWithOneTimeCode(66) - registring with code: uoypwjbs
4/15/2022 9:30:53 AM	RmCloudDataSource.Request(212) - url is: https://webapp-production-dot-remarkable-production.appspot.com/token/json/2/device/new
4/15/2022 9:34:53 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "appkey" failed
4/15/2022 9:34:53 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "hmackey" failed
4/15/2022 9:35:04 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "CustomDeviceTokenUrl" failed
4/15/2022 9:35:04 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "CustomUserTokenUrl" failed
4/15/2022 9:35:04 AM	WinRegistryConfigStore.GetConfig(37) - Getting value from registry for config "CustomBaseUrl" failed
4/15/2022 9:35:04 AM	RmDownloadForm.InitializeData(91) - Using rm cloud data source
4/15/2022 9:35:04 AM	RmCloudDataSource.Initialize(179) - device token loaded from config file
4/15/2022 9:35:04 AM	RmCloudDataSource.Request(212) - url is: https://webapp-production-dot-remarkable-production.appspot.com/token/json/2/user/new
4/15/2022 9:35:05 AM	RmCloudDataSource.RenewToken(250) - user token renewed
4/15/2022 9:35:05 AM	RmCloudDataSource.Request(212) - url is: https://document-storage-production-dot-remarkable-production.appspot.com/document-storage/json/2/docs
4/15/2022 9:35:05 AM	RmCloudDataSource.GetAllItems(116) - Request failed with status code: Unauthorized and content: 
4/15/2022 9:35:05 AM	RmDownloadForm.InitializeData(99) - Error getting notebook structure from reMarkable. Err: GetAllItems request failed with status code Unauthorized
`

I tried the SSH and it does work fine.

**Comment by jamesf91** [comment]
From the log, the first run at 9:20 looks like it was not configured correctly as the device token was missing. I will ignore this run for now.

For the 2nd run at 9:34:
The code first uses the saved device token to request for a new user token (i.e a session token) from remarkable cloud. This completed successfully.  
It then tried to use the session token to get the file list data from the cloud but that failed with an Unauthorized error.

I'm suspecting that the issue the same as [this issue here](https://github.com/juruen/rmapi/issues/187), where remarkable apparently has 2 api now. Newer users might be on the new API while older users are still on the original API. (I've confirmed that I'm still on the old API),

I can try to implement the new API as per rmapi but given I can't test it, it will be difficult for me to get it working. I will have a go at it but I suggest stick to ssh for now.

**Comment by kcossabo** [comment]
Thank you for having a look. The App is EXCELLENT and I appreciate all your efforts.

I can see the value of the cloud attach (I can just do it), but the cord works fine, and IP Connection would be as good as a cloud.

**Comment by mtna555** [comment]
I setup my remakable and my sync last week so I suspect I am on the new api.  I am using SSH for now.  If there is anything I can provide (logs, remote access, etc) that will help you get this working let me know.

**Comment by cplager** [comment]
Where are the instructions for setting up SSH connection?  (Where do I set password? Do I leave blank if device is not password protected?)

Thanks!

**Comment by kcossabo** [comment]
> Where are the instructions for setting up SSH connection? (Where do I set password? Do I leave blank if device is not password protected?)
> 
> Thanks!

Menu -> Security -> Passcode -> on
Menu - > Help -> Copyright and licenses -> part of the GPLv3 Compliance statement you will see root password

**Comment by tripp396** [comment]
> From the log, the first run at 9:20 looks like it was not configured correctly as the device token was missing. I will ignore this run for now.
> 
> For the 2nd run at 9:34: The code first uses the saved device token to request for a new user token (i.e a session token) from remarkable cloud. This completed successfully. It then tried to use the session token to get the file list data from the cloud but that failed with an Unauthorized error.
> 
> I'm suspecting that the issue the same as [this issue here](https://github.com/juruen/rmapi/issues/187), where remarkable apparently has 2 api now. Newer users might be on the new API while older users are still on the original API. (I've confirmed that I'm still on the old API),
> 
> I can try to implement the new API as per rmapi but given I can't test it, it will be difficult for me to get it working. I will have a go at it but I suggest stick to ssh for now.

If you need anyone to help test, I will volunteer. Wonderful looking app, and would love to get this to work.

**Comment by Shrekmachine** [comment]
Hi, any update on this issue?

**Comment by chad-mcdonald616** [comment]
@jamesf91  Thanks for all your work in this it really is a neat integration. I am also on the new API and receiving the same error message as the others.  I can confirm that the USB SSH method does still work just fine so that is what I am using now.  If there is any way we can provide detail or logs to help get the cloud sync working again please let us know!  Happy to help out!

**Comment by jamesf91** [comment]
Hi everyone. Sorry for the delay, I've been really busy for the last few month.
Good news, I'm finally on the new API myself so I can start creating the new api client.
Might take a few weeks to get the code ready and tested.

**Comment by Jeffm5496** [comment]
I’m getting an error on SSH too and using the correct password.

**Comment by asaintvip** [comment]
I started a new thread, but I'll leave a message here to be included on any news of the updates for the new API. I'm also getting the "Unauthorized" error when I try to fetch my notebook. Thanks for the assistance.

**Comment by jamesf91** [comment]
v3.0.0 is now released with the fix to support the new rm cloud api.

**Comment by Shrekmachine** [comment]
Works :)

**Comment by cplager** [comment]
Not only does it work now, the "both image and text" option is now available.  This is **fabulous.**  Well done!
