### ISSUE TITLE
ssh by wifi

### ISSUE THREAD

**Issue by piforce** [jamesf91/RemarkableSync#3]
Is it possible to acces the remarkable by wifi ssh acces. Is there a way that i can point to my ip adress (with wifi) of the tablet instead of the usb ip adress?

**Comment by Delscout** [comment]
Hi, this is just what I was after, does it work with Onenote for Windows 10 - although it installs with no errors it does not give me a "Remarkable" tab on the ribbon

**Comment by jamesf91** [comment]
@piforce, that should be possible. The backend already support arbitrary IP address for ssh instead of the 10.x.x.x usb IP. However I need to find some time to do a config screen UI change to expose that setting. 

I will plan it into the next change
