### ISSUE TITLE
Intergration broken when using Remarkable beta?

### ISSUE THREAD

**Issue by carlo0501** [jamesf91/RemarkableSync#32]
Plugin yesterday complained that a new integration was needed.
I installed latest version and followed instruction.
When I insert the one-time code provided by Remarkable web site, integration is apparently successful ("new device added", etc. etc.)
However, when I try to fetch the contents of my Remarkable I'm always getting the attached error message.
![image](https://user-images.githubusercontent.com/104497367/165493382-ab0cb178-8f53-4086-ad4e-0ae73c3947cf.png)
I'm also attaching a log file with some attempts done yesterday.
[remarkable_sync_log.txt](https://github.com/jamesf91/reMarkableSync/files/8571013/remarkable_sync_log.txt)
Do you happen to know if Remarkable beta version (I'm on 2.12.3.606) are blocked from integrating with 3rd party software?

 - Carlo

**Comment by bratland** [comment]
I get the same problem.

**Comment by mdurini-swisscom** [comment]
Same here.

**Comment by downingdn** [comment]
+1. New user, on rm2, 64-bit, Version 2.13.0.758. Not in beta program.
If it helps, once I have done "apply" with one time pass code, the apply button greys out, then onenote tells me that it is registered (Success: "New reMarkable device registered successfully"). But then the field goes blank again, as if I had never entered the one-time code. (Same with the myscript).

Installpath = Microsoft.NET\Framework64\v4.0.30319\
Version = 4.8.04084

Tried uninstall/reinstall

Are there regedit settings I can look for where the key is stored? Maybe delete and reinstall those?

**Comment by carlo0501** [comment]
This issue has nothing to do with Remarkable beta program
