### ISSUE TITLE
Remarkable SSH setup?

### ISSUE THREAD

**Issue by karlek36** [jamesf91/RemarkableSync#5]
How do I figure out the code for my remarkable SSH set up?

**Comment by jamesf91** [comment]
@karlek36, to get the device specific SSH password, on your device, go to Menu -> Settings -> Help -> Copyrights and licenses. Under the section "GPLv3 Compliance" you will see text like:
... you can connect using the SSH protocol using the username 'root' and the password 'xxx'.
