### ISSUE TITLE
GetAllItems request failed with status code Unauthorized

### ISSUE THREAD

**Issue by ParkerP2** [jamesf91/RemarkableSync#6]
When attempting to fetch items using the latest installer and OneNote from 365 build 16.0.14026.20270 (64-bit) I receive the error below-

![remarkable](https://user-images.githubusercontent.com/22865108/122285186-69d9ff80-cebc-11eb-8fc3-128c07052785.png)

I've attempted to resolve by re-installing the addin and a fresh OneNote install, along with re-generating a new cloud code. When registering in the web I still only see '1 Connected' Desktop App that should be the reMarkable app.

**Comment by jamesf91** [comment]
Hi @ParkerP2, thanks for noticing this. Looks like remarkable changed their device authentication URL according to https://github.com/juruen/rmapi/pull/178.
I will be pushing a fix with the updated url soon
